module.exports = [
  // Languages
  "javascript",
  "typescript",
  "python",
  "java",
  "c",
  "cpp",
  "csharp",
  "go",
  "ruby",
  "php",
  "kotlin",
  "swift",
  "dart",
  "rust",
  "scala",
  "r",
  "perl",
  "lua",
  "haskell",
  "elixir",
  "clojure",
  "fsharp",
  "vbnet",
  "objective-c",
  "bash",
  "zsh",
  "powershell",
  "groovy",
  "erlang",
  "assembly",
  "nasm",
  "matlab",
  "octave",
  "julia",
  "nim",
  "crystal",
  "zig",
  "vala",
  "fortran",
  "ada",
  "pascal",
  "delphi",
  "coffeescript",
  "smalltalk",
  "lisp",
  "scheme",
  "prolog",
  "ocaml",
  "tcl",
  "awk",
  "sed",
  "sml",
  "d",
  "vhdl",
  "verilog",
  "opencl",
  "glsl",
  "sql",
  "plsql",
  "cypher",
  "sparql",
  "rpg",
  "cobol",
  "red",
  "rebol",
  "pony",
  "idris",
  "agda",
  "elm",
  "purescript",
  "livescript",
  "nix",
  "hack",
  "actionscript",
  "ml",
  "qsharp",
  "apl",
  "j",
  "sas",
  "stata",
  "vbscript",
  "abap",
  "modelica",
  "blitzmax",
  "harbour",
  "xharbour",
  "euphoria",
  "io",
  "bc",
  "picat",
  "ring",
  "terra",
  "logtalk",
  "genie",
  "icon",
  "falcon",
  "factor",
  "inform",
  "pike",
  "m4",
  "xtend",
  "xtlang",
  "gml",
  "gdscript",
  "haxe",
  "renpy",
  "papyrus",
  "angelscript",
  "pawn",
  "quakec",
  "brainfuck",
  "whitespace",
  "lolcode",
  "befunge",
  "malbolge",
  "shakespeare",

  // Frontend
  "react",
  "vue",
  "angular",
  "svelte",
  "nextjs",
  "nuxtjs",
  "astro",
  "jquery",
  "solidjs",
  "lit",
  "preact",
  "ember",
  "alpinejs",
  "stimulus",
  "htmx",
  "marko",
  "mithril",
  "riot",
  "backbone",
  "dojo",
  "quasar",
  "vitepress",
  "gridsome",
  "gatsby",
  "eleventy",
  "remix",
  "blitzjs",
  "redwoodjs",
  "qwik",
  "stencil",
  "riotjs",
  "inferno",
  "recoil",
  "mobx",
  "zustand",

  // Backend
  "express",
  "nestjs",
  "laravel",
  "springboot",
  "rails",
  "django",
  "flask",
  "fastapi",
  "adonisjs",
  "hapi",
  "koa",
  "sails",
  "loopback",
  "feathers",
  "strapi",
  "meteor",
  "blitzjs",
  "redwoodjs",
  "nextjs", // SSR API Routes
  "nuxtjs", // SSR API Routes
  "remix",
  "gin",
  "echo",
  "fiber",
  "actix",
  "rocket",
  "phoenix",
  "micronaut",
  "quarkus",
  "vertx",
  "play",
  "ktor",
  "beego",
  "revel",
  "symfony",
  "codeigniter",
  "cakephp",
  "yii",
  "slim",
  "pyramid",
  "tornado",
  "web2py",
  "bottle",
  "sanic",
  "falcon",
  "uvicorn",
  "plug",
  "nitro",
  "masonite",
  "ninja",
  "dotnetcore",
  "aspnet",
  "buffalo",
  "vapor", // Swift backend

  // Mobile
  "flutter",
  "reactnative",
  "electron", // Desktop & Mobile hybrid
  "capacitor",
  "cordova",
  "nativescript",
  "expo",
  "ionic",
  "xamarin",
  "unity", // Game + mobile app dev
  "nativeandroid", // Java/Kotlin with Android SDK
  "nativeios", // Swift/Obj-C with iOS SDK
  "kmm", // Kotlin Multiplatform Mobile
  "mauraui", // .NET MAUI for mobile & desktop
  "quasar", // Vue-based, with mobile support
  "tauri", // Lightweight alternative to Electron
  "felgo", // Qt-based mobile dev
  "weex", // Alibaba's cross-platform framework
  "monaca", // Hybrid framework using Cordova
  "tabrisjs", // JS + Native APIs (lightweight)

  // Database
  "mysql",
  "postgresql",
  "sqlite",
  "mariadb",
  "oracle",
  "sqlserver",
  "mongodb",
  "couchdb",
  "pouchdb",
  "redis",
  "memcached",
  "cassandra",
  "scylladb",
  "clickhouse",
  "timescaledb",
  "influxdb",
  "prometheus",
  "dynamodb",
  "arangodb",
  "neo4j",
  "janusgraph",
  "faunadb",
  "rqlite",
  "etcd",
  "leveldb",
  "rocksdb",
  "realm",
  "firebase",
  "supabase",
  "tidb",
  "hbase",
  "bigtable",
  "duckdb",
  "trino",
  "presto",
  "firebird",
  "db2",
  "vitess",
  "harperdb",
  "cockroachdb",

  // DevOps
  "docker",
  "kubernetes",
  "podman",
  "containerd",
  "runc",
  "dockercompose",
  "jenkins",
  "githubactions",
  "gitlabci",
  "circleci",
  "travisci",
  "teamcity",
  "droneci",
  "buildkite",
  "azurepipelines",
  "bitbucketpipelines",
  "spinnaker",
  "argo",
  "tekton",
  "terraform",
  "pulumi",
  "cloudformation",
  "ansible",
  "chef",
  "puppet",
  "saltstack",
  "packer",
  "vagrant",
  "helm",
  "kustomize",
  "fluxcd",
  "crossplane",
  "vault",
  "consul",
  "nomad",
  "prometheus",
  "grafana",
  "datadog",
  "newrelic",
  "zabbix",
  "nagios",
  "elasticstack",
  "loki",
  "jaeger",
  "otel", // OpenTelemetry
  "istio",
  "linkerd",
  "cilium",
  "kong",
  "traefik",
  "nginx",
  "haproxy",

  // Testing
  "jest",
  "mocha",
  "chai",
  "vitest",
  "jasmine",
  "ava",
  "tape",
  "uvu",
  "qunit",
  "cypress",
  "playwright",
  "puppeteer",
  "selenium",
  "webdriverio",
  "testcafe",
  "nightwatch",
  "karma",
  "enzyme",
  "reacttestinglibrary",
  "testinglibrary",
  "nock",
  "msw",
  "sinon",
  "supertest",
  "postman",
  "newman",
  "pytest",
  "unittest",
  "nose",
  "doctest",
  "robotframework",
  "rspec",
  "minitest",
  "xunit",
  "nunit",
  "junit",
  "testng",
  "catch2",
  "googletest",
  "doctestcpp",
  "kotest",
  "spek",
  "mockk",
  "mockito",
  "mockery",
  "phpunit",
  "behat",
  "codeception",
  "bats",

  // Tools
  "axios",
  "got",
  "ky",
  "nodefetch",
  "swr",
  "reactquery",
  "tanstackquery",
  "lodash",
  "underscore",
  "ramda",
  "datefns",
  "moment",
  "dayjs",
  "luxon",
  "chalk",
  "colors",
  "ora",
  "figlet",
  "dotenv",
  "crossenv",
  "concurrently",
  "nodemon",
  "pm2",
  "eslint",
  "tslint",
  "stylelint",
  "prettier",
  "husky",
  "lintstaged",
  "webpack",
  "vite",
  "babel",
  "rollup",
  "esbuild",
  "parcel",
  "swc",
  "turbo",
  "nx",
  "tsup",
  "rimraf",
  "nanoid",
  "uuid",
  "zx",
  "tsnode",
  "tsconfigpaths",
  "dotenvexpand",
  "envsafe",

  // Concepts
  "graphql",
  "restapi",
  "jwt",
  "oauth",
  "websocket",
  "pwa", // Progressive Web Apps
  "ssr", // Server-side Rendering
  "ssg", // Static Site Generation
  "csr", // Client-side Rendering
  "microservices",
  "monorepo",
  "i18n", // Internationalization
  "l10n", // Localization
  "cdn", // Content Delivery Network
  "api-first",
  "event-driven",
  "serverless",
  "edgecomputing",
  "lambda",
  "ci_cd", // Continuous Integration & Continuous Deployment
  "devops",
  "gitops",
  "event-sourcing",
  "cqrs", // Command Query Responsibility Segregation
  "asyncapi",
  "webhooks",
  "tdd", // Test-Driven Development
  "bdd", // Behavior-Driven Development
  "domain-driven-design",
  "clean-architecture",
  "hexagonal-architecture",
  "mvc", // Model-View-Controller
  "mvvm", // Model-View-ViewModel
  "component-based", // Component-Based Architecture
  "monolithic", // Monolithic Architecture
  "scalable-architecture",
  "responsive-design",
  "mobile-first", // Mobile-First Design
  "caching-strategy",
  "load-balancing",
  "api-gateway",
  "service-mesh",
  "containerization",
  "orchestration",
  "micro-frontends",
  "progressive-enhancement",
  "lazy-loading",
  "code-splitting",
  "hot-reloading",
  "service-oriented-architecture", // SOA
  "unidirectional-data-flow",
  "functional-programming",
  "object-oriented-programming",
  "reactive-programming",
  "immutable-data",
];
